name: Automatic Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build extension
      run: |
        mkdir -p build
        cp -r manifest.json background.js content.js popup.html popup.js styles.css icons/ lib/ README.md privacy_policy.md build/
        cd build
        zip -r ../bili_danmu_ext.zip .
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: bili-danmu-extension
        path: bili_danmu_ext.zip
        retention-days: 90
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: bili_danmu_ext.zip
        name: 自动构建版本 ${{ github.sha }}
        body: 最新的自动构建版本
        prerelease: true
        tag_name: build-${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}